### Create Partner
POST http://localhost:8081/partners
Content-Type: application/json

{
  "name": "John"
}

### Get all Partners
GET http://localhost:8081/partners
Content-Type: application/json

### Get One Partner
GET http://localhost:8081/partners/1
Content-Type: application/json
